apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oidc-discovery.fullname" . }}
  labels:
    {{- include "oidc-discovery.labels" . | nindent 4 }}
data:
  config: |
    {{ .Values.oidc.config | b64dec }}
  keys: |
    {{ .Values.oidc.keys | b64dec }}
