---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "oidc-discovery.fullname" . }}
  labels:
    {{- include "oidc-discovery.labels" . | nindent 4 }}
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: garden
      podSelector:
        matchLabels:
          app: nginx-ingress
          component: controller
    ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  podSelector:
    matchLabels:
      {{- include "oidc-discovery.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    {{- include "oidc-discovery.labels" . | nindent 4 }}
  name: {{ include "oidc-discovery.fullname" . }}
  namespace: garden
spec:
  egress:
  - ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
    to:
    - podSelector:
        matchLabels:
          {{- include "oidc-discovery.selectorLabels" . | nindent 10 }}
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Release.Namespace }}
  podSelector:
    matchLabels:
      app: nginx-ingress
      component: controller
  policyTypes:
  - Egress
